# Auto-label PRs based on changed files
'area: core':
- any: ['*.php', '*.sh', '*.txt']

'area: tests':
- any: ['tests/**']

'area: docs':
- any: ['*.md', 'docs/**']

'area: ci/cd':
- any: ['.github/**']

'area: dependencies':
- any: ['composer*.json', 'composer*.lock']

'area: config':
- any: ['*.dist', '*.json', '*.xml', '*.yml', '*.yaml']
